USE ROLE RETAIL_DEMO_ENGINEER;
USE WAREHOUSE RETAIL_DEMO_WH;
USE DATABASE RETAIL_DEMO;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE DYNAMIC TABLE ITEM_STORE_BASELINE
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = RETAIL_DEMO_WH
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
SELECT
  ss.SS_STORE_SK AS STORE_SK,
  ss.SS_ITEM_SK AS ITEM_SK,
  SUM(ss.SS_QUANTITY) / s.BASELINE_DAYS AS AVG_DAILY_UNITS,
  SUM(ss.SS_EXT_SALES_PRICE) / s.BASELINE_DAYS AS AVG_DAILY_SALES,
  SUM(ss.SS_NET_PROFIT) / s.BASELINE_DAYS AS AVG_DAILY_MARGIN,
  STDDEV_POP(ss.SS_QUANTITY) AS UNIT_VARIABILITY
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES ss
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM d
  ON d.D_DATE_SK = ss.SS_SOLD_DATE_SK
JOIN RETAIL_DEMO.CONFIG.DEMO_SCENARIO_ITEM i ON i.ITEM_SK = ss.SS_ITEM_SK
JOIN RETAIL_DEMO.CONFIG.DEMO_SCENARIO_STORE st ON st.STORE_SK = ss.SS_STORE_SK
CROSS JOIN RETAIL_DEMO.CONFIG.DEMO_SCENARIO s
WHERE d.D_DATE BETWEEN s.BASELINE_START_DATE AND s.BASELINE_END_DATE
GROUP BY ss.SS_STORE_SK, ss.SS_ITEM_SK, s.BASELINE_DAYS;

CREATE OR REPLACE DYNAMIC TABLE ITEM_STORE_DAY
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = RETAIL_DEMO_WH
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
WITH SALES AS (
  SELECT
    TO_DATE(EVENT_TS) AS BUSINESS_DATE,
    STORE_SK,
    ITEM_SK,
    SUM(UNITS) AS UNITS,
    SUM(SALES_AMOUNT) AS SALES_AMOUNT,
    SUM(NET_PAID) AS NET_PAID
  FROM RETAIL_DEMO.RAW.STORE_SALES_EVENTS
  GROUP BY TO_DATE(EVENT_TS), STORE_SK, ITEM_SK
),
INVENTORY AS (
  SELECT
    TO_DATE(EVENT_TS) AS BUSINESS_DATE,
    STORE_SK,
    ITEM_SK,
    ON_HAND_QTY,
    ON_ORDER_QTY,
    IN_TRANSIT_QTY
  FROM RETAIL_DEMO.RAW.STORE_INVENTORY_EVENTS
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TO_DATE(EVENT_TS), STORE_SK, ITEM_SK ORDER BY EVENT_TS DESC, INGESTED_AT DESC
  ) = 1
)
SELECT
  s.BUSINESS_DATE,
  s.STORE_SK,
  s.ITEM_SK,
  s.UNITS,
  s.SALES_AMOUNT,
  s.NET_PAID,
  i.ON_HAND_QTY,
  i.ON_ORDER_QTY,
  i.IN_TRANSIT_QTY
FROM SALES s
JOIN INVENTORY i
  ON i.BUSINESS_DATE = s.BUSINESS_DATE
 AND i.STORE_SK = s.STORE_SK
 AND i.ITEM_SK = s.ITEM_SK;

CREATE OR REPLACE DYNAMIC TABLE SUPPLIER_PERFORMANCE_CURRENT
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = RETAIL_DEMO_WH
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
SELECT
  p.SUPPLIER_ID,
  p.STORE_SK,
  p.ITEM_SK,
  SUM(p.ORDERED_QTY) AS ORDERED_QTY,
  SUM(COALESCE(r.RECEIVED_QTY, 0)) AS RECEIVED_QTY,
  SUM(COALESCE(r.RECEIVED_QTY, 0)) / NULLIF(SUM(p.ORDERED_QTY), 0) AS FILL_RATE,
  MAX(p.EXPECTED_RECEIPT_DATE) AS LATEST_EXPECTED_RECEIPT_DATE,
  MAX(r.RECEIPT_DATE) AS LATEST_RECEIPT_DATE
FROM RETAIL_DEMO.RAW.PURCHASE_ORDER p
LEFT JOIN RETAIL_DEMO.RAW.RECEIPT r ON r.PO_ID = p.PO_ID
GROUP BY p.SUPPLIER_ID, p.STORE_SK, p.ITEM_SK;

CREATE OR REPLACE DYNAMIC TABLE ITEM_STORE_HEALTH
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = RETAIL_DEMO_WH
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
WITH LATEST AS (
  SELECT *
  FROM ITEM_STORE_DAY
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY STORE_SK, ITEM_SK ORDER BY BUSINESS_DATE DESC
  ) = 1
),
CALCULATED AS (
  SELECT
    l.BUSINESS_DATE,
    l.STORE_SK,
    l.ITEM_SK,
    p.SUPPLIER_ID,
    b.AVG_DAILY_UNITS,
    b.AVG_DAILY_SALES,
    b.AVG_DAILY_MARGIN,
    l.ON_HAND_QTY,
    l.ON_ORDER_QTY,
    l.IN_TRANSIT_QTY,
    l.ON_HAND_QTY / NULLIF(b.AVG_DAILY_UNITS, 0) AS DAYS_OF_SUPPLY,
    p.FILL_RATE,
    GREATEST(0, (2 * b.AVG_DAILY_UNITS) - l.ON_HAND_QTY) AS UNITS_AT_RISK,
    b.AVG_DAILY_SALES / NULLIF(b.AVG_DAILY_UNITS, 0) AS UNIT_RETAIL,
    b.AVG_DAILY_MARGIN / NULLIF(b.AVG_DAILY_UNITS, 0) AS UNIT_MARGIN
  FROM LATEST l
  JOIN ITEM_STORE_BASELINE b
    ON b.STORE_SK = l.STORE_SK AND b.ITEM_SK = l.ITEM_SK
  LEFT JOIN SUPPLIER_PERFORMANCE_CURRENT p
    ON p.STORE_SK = l.STORE_SK AND p.ITEM_SK = l.ITEM_SK
)
SELECT
  *,
  IFF(DAYS_OF_SUPPLY <= 2, 'AT_RISK', 'HEALTHY') AS HEALTH_STATUS,
  ROUND(UNITS_AT_RISK * UNIT_RETAIL, 2) AS ESTIMATED_LOST_SALES,
  ROUND(UNITS_AT_RISK * UNIT_MARGIN, 2) AS ESTIMATED_LOST_MARGIN
FROM CALCULATED;

CREATE OR REPLACE DYNAMIC TABLE CATEGORY_STORE_DAY
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = RETAIL_DEMO_WH
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
SELECT
  d.BUSINESS_DATE,
  d.STORE_SK,
  i.CATEGORY,
  SUM(d.UNITS) AS UNITS,
  SUM(d.SALES_AMOUNT) AS SALES_AMOUNT,
  MAX(p.SALES_PLAN) AS SALES_PLAN,
  SUM(d.SALES_AMOUNT) - MAX(p.SALES_PLAN) AS SALES_TO_PLAN_VARIANCE
FROM ITEM_STORE_DAY d
JOIN RETAIL_DEMO.CONFIG.DEMO_SCENARIO_ITEM i ON i.ITEM_SK = d.ITEM_SK
LEFT JOIN RETAIL_DEMO.RAW.MERCHANT_PLAN p
  ON p.PLAN_DATE = d.BUSINESS_DATE
 AND p.STORE_SK = d.STORE_SK
 AND p.CATEGORY = i.CATEGORY
GROUP BY d.BUSINESS_DATE, d.STORE_SK, i.CATEGORY;

CREATE OR REPLACE DYNAMIC TABLE MERCHANT_SCORECARD
  TARGET_LAG = '5 minutes'
  WAREHOUSE = RETAIL_DEMO_WH
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
SELECT
  h.BUSINESS_DATE,
  i.CATEGORY,
  COUNT(*) AS ITEM_STORE_COUNT,
  COUNT_IF(h.HEALTH_STATUS = 'AT_RISK') AS AT_RISK_COUNT,
  ROUND(SUM(h.ESTIMATED_LOST_SALES), 2) AS ESTIMATED_LOST_SALES,
  ROUND(SUM(h.ESTIMATED_LOST_MARGIN), 2) AS ESTIMATED_LOST_MARGIN,
  ROUND(AVG(h.DAYS_OF_SUPPLY), 2) AS AVG_DAYS_OF_SUPPLY,
  ROUND(AVG(h.FILL_RATE), 4) AS AVG_SUPPLIER_FILL_RATE
FROM ITEM_STORE_HEALTH h
JOIN RETAIL_DEMO.CONFIG.DEMO_SCENARIO_ITEM i ON i.ITEM_SK = h.ITEM_SK
GROUP BY h.BUSINESS_DATE, i.CATEGORY;

CREATE OR REPLACE DYNAMIC TABLE MERCHANT_PROBLEMS
  TARGET_LAG = '5 minutes'
  WAREHOUSE = RETAIL_DEMO_WH
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
SELECT
  h.BUSINESS_DATE,
  h.STORE_SK,
  h.ITEM_SK,
  i.CATEGORY,
  h.SUPPLIER_ID,
  h.DAYS_OF_SUPPLY,
  h.FILL_RATE,
  h.ESTIMATED_LOST_SALES,
  h.ESTIMATED_LOST_MARGIN,
  CASE
    WHEN h.FILL_RATE < 0.80 AND h.DAYS_OF_SUPPLY <= 2 THEN 'SUPPLIER_UNDERFILL'
    WHEN h.DAYS_OF_SUPPLY <= 2 THEN 'INVENTORY_DEPLETION'
    ELSE 'NO_ACTIVE_PROBLEM'
  END AS ROOT_CAUSE,
  ROW_NUMBER() OVER (
    ORDER BY h.ESTIMATED_LOST_SALES DESC, h.STORE_SK, h.ITEM_SK
  ) AS IMPACT_RANK
FROM ITEM_STORE_HEALTH h
JOIN RETAIL_DEMO.CONFIG.DEMO_SCENARIO_ITEM i ON i.ITEM_SK = h.ITEM_SK
WHERE h.HEALTH_STATUS = 'AT_RISK';

CREATE OR REPLACE DYNAMIC TABLE ROOT_CAUSE_EVIDENCE
  TARGET_LAG = '5 minutes'
  WAREHOUSE = RETAIL_DEMO_WH
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
AS
SELECT
  p.BUSINESS_DATE,
  p.STORE_SK,
  st.STORE_ID,
  st.STORE_NAME,
  p.ITEM_SK,
  i.ITEM_ID,
  i.ITEM_DESC,
  p.CATEGORY,
  p.SUPPLIER_ID,
  s.SUPPLIER_NAME,
  p.ROOT_CAUSE,
  p.DAYS_OF_SUPPLY,
  p.FILL_RATE,
  b.AVG_DAILY_UNITS,
  h.ON_HAND_QTY,
  h.ON_ORDER_QTY,
  p.ESTIMATED_LOST_SALES,
  p.ESTIMATED_LOST_MARGIN,
  p.IMPACT_RANK
FROM MERCHANT_PROBLEMS p
JOIN ITEM_STORE_HEALTH h
  ON h.STORE_SK = p.STORE_SK AND h.ITEM_SK = p.ITEM_SK
JOIN ITEM_STORE_BASELINE b
  ON b.STORE_SK = p.STORE_SK AND b.ITEM_SK = p.ITEM_SK
JOIN RETAIL_DEMO.CONFIG.DEMO_SCENARIO_ITEM i ON i.ITEM_SK = p.ITEM_SK
JOIN RETAIL_DEMO.CONFIG.DEMO_SCENARIO_STORE st ON st.STORE_SK = p.STORE_SK
LEFT JOIN RETAIL_DEMO.RAW.SUPPLIER s ON s.SUPPLIER_ID = p.SUPPLIER_ID;
