-- Run once with a role allowed to create roles, warehouses, resource monitors,
-- databases, and grants. Daily tutorial work uses RETAIL_DEMO_ENGINEER.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS RETAIL_DEMO_ENGINEER
  COMMENT = 'Build role for the Merchant Decision Intelligence tutorial';
CREATE ROLE IF NOT EXISTS RETAIL_DEMO_METABASE
  COMMENT = 'Read-only serving role for the tutorial dashboard';

CREATE RESOURCE MONITOR IF NOT EXISTS RETAIL_DEMO_MONITOR
  WITH CREDIT_QUOTA = 25
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE WAREHOUSE IF NOT EXISTS RETAIL_DEMO_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = RETAIL_DEMO_MONITOR
  COMMENT = 'Disposable tutorial warehouse';

CREATE DATABASE IF NOT EXISTS RETAIL_DEMO
  COMMENT = 'Merchant Decision Intelligence tutorial';

CREATE SCHEMA IF NOT EXISTS RETAIL_DEMO.CONFIG;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEMO.SEED;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEMO.RAW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEMO.LAKEHOUSE;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEMO.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEMO.SERVING;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEMO.VALIDATION;

GRANT USAGE, OPERATE ON WAREHOUSE RETAIL_DEMO_WH TO ROLE RETAIL_DEMO_ENGINEER;
GRANT USAGE ON DATABASE RETAIL_DEMO TO ROLE RETAIL_DEMO_ENGINEER;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA
  TO ROLE RETAIL_DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE RETAIL_DEMO
  TO ROLE RETAIL_DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE RETAIL_DEMO
  TO ROLE RETAIL_DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE RETAIL_DEMO
  TO ROLE RETAIL_DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE RETAIL_DEMO
  TO ROLE RETAIL_DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE DYNAMIC TABLES IN DATABASE RETAIL_DEMO
  TO ROLE RETAIL_DEMO_ENGINEER;

GRANT USAGE ON DATABASE RETAIL_DEMO TO ROLE RETAIL_DEMO_METABASE;
GRANT USAGE ON SCHEMA RETAIL_DEMO.SERVING TO ROLE RETAIL_DEMO_METABASE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RETAIL_DEMO.SERVING TO ROLE RETAIL_DEMO_METABASE;

GRANT ROLE RETAIL_DEMO_ENGINEER TO USER <% user_name %>;
GRANT ROLE RETAIL_DEMO_METABASE TO USER <% metabase_user_name %>;

USE WAREHOUSE RETAIL_DEMO_WH;
USE DATABASE RETAIL_DEMO;
USE SCHEMA CONFIG;
SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();
