USE ROLE RETAIL_DEMO_ENGINEER;
USE WAREHOUSE RETAIL_DEMO_WH;
USE DATABASE RETAIL_DEMO;

CREATE FILE FORMAT IF NOT EXISTS SEED.PARQUET_FORMAT
  TYPE = PARQUET
  USE_LOGICAL_TYPE = TRUE;

CREATE FILE FORMAT IF NOT EXISTS SEED.JSONL_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE STAGE IF NOT EXISTS SEED.S3_LANDING_STAGE
  URL = '<% s3_landing_url %>'
  STORAGE_INTEGRATION = RETAIL_DEMO_S3_INTEGRATION
  DIRECTORY = (ENABLE = TRUE);

LIST @SEED.S3_LANDING_STAGE;
