USE ROLE RETAIL_DEMO_ENGINEER;
USE WAREHOUSE RETAIL_DEMO_WH;
USE DATABASE RETAIL_DEMO;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS SUPPLIER (
  SUPPLIER_ID VARCHAR NOT NULL,
  SUPPLIER_NAME VARCHAR NOT NULL,
  SUPPLIER_TIER VARCHAR NOT NULL,
  ACTIVE BOOLEAN NOT NULL,
  INGESTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT SUPPLIER_PK PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE IF NOT EXISTS PURCHASE_ORDER (
  PO_ID VARCHAR NOT NULL,
  SUPPLIER_ID VARCHAR NOT NULL,
  STORE_SK NUMBER NOT NULL,
  ITEM_SK NUMBER NOT NULL,
  ORDER_DATE DATE NOT NULL,
  EXPECTED_RECEIPT_DATE DATE NOT NULL,
  ORDERED_QTY NUMBER NOT NULL,
  STATUS VARCHAR NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ NOT NULL,
  INGESTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PURCHASE_ORDER_PK PRIMARY KEY (PO_ID)
);

CREATE TABLE IF NOT EXISTS RECEIPT (
  RECEIPT_ID VARCHAR NOT NULL,
  PO_ID VARCHAR NOT NULL,
  RECEIPT_DATE DATE NOT NULL,
  RECEIVED_QTY NUMBER NOT NULL,
  REJECTED_QTY NUMBER NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ NOT NULL,
  INGESTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT RECEIPT_PK PRIMARY KEY (RECEIPT_ID)
);

CREATE TABLE IF NOT EXISTS MERCHANT_PLAN (
  PLAN_ID VARCHAR NOT NULL,
  PLAN_DATE DATE NOT NULL,
  STORE_SK NUMBER NOT NULL,
  CATEGORY VARCHAR NOT NULL,
  SALES_PLAN NUMBER(18,2) NOT NULL,
  MARGIN_PLAN NUMBER(18,2) NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ NOT NULL,
  INGESTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT MERCHANT_PLAN_PK PRIMARY KEY (PLAN_ID)
);

CREATE TABLE IF NOT EXISTS STORE_SALES_EVENTS (
  EVENT_ID VARCHAR NOT NULL,
  EVENT_TS TIMESTAMP_NTZ NOT NULL,
  STORE_SK NUMBER NOT NULL,
  ITEM_SK NUMBER NOT NULL,
  UNITS NUMBER NOT NULL,
  SALES_AMOUNT NUMBER(18,2) NOT NULL,
  DISCOUNT_AMOUNT NUMBER(18,2) NOT NULL,
  NET_PAID NUMBER(18,2) NOT NULL,
  INGESTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT STORE_SALES_EVENTS_PK PRIMARY KEY (EVENT_ID)
);

CREATE TABLE IF NOT EXISTS STORE_INVENTORY_EVENTS (
  EVENT_ID VARCHAR NOT NULL,
  EVENT_TS TIMESTAMP_NTZ NOT NULL,
  STORE_SK NUMBER NOT NULL,
  ITEM_SK NUMBER NOT NULL,
  ON_HAND_QTY NUMBER NOT NULL,
  ON_ORDER_QTY NUMBER NOT NULL,
  IN_TRANSIT_QTY NUMBER NOT NULL,
  INGESTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT STORE_INVENTORY_EVENTS_PK PRIMARY KEY (EVENT_ID)
);
