USE ROLE RETAIL_DEMO_ENGINEER;
USE WAREHOUSE RETAIL_DEMO_WH;
USE DATABASE RETAIL_DEMO;
USE SCHEMA RAW;

CREATE PIPE IF NOT EXISTS STORE_SALES_EVENTS_PIPE
AS COPY INTO STORE_SALES_EVENTS
  (EVENT_ID, EVENT_TS, STORE_SK, ITEM_SK, UNITS, SALES_AMOUNT,
   DISCOUNT_AMOUNT, NET_PAID)
FROM (
  SELECT
    $1:event_id::VARCHAR,
    $1:event_ts::TIMESTAMP_NTZ,
    $1:store_sk::NUMBER,
    $1:item_sk::NUMBER,
    $1:units::NUMBER,
    $1:sales_amount::NUMBER(18,2),
    $1:discount_amount::NUMBER(18,2),
    $1:net_paid::NUMBER(18,2)
  FROM TABLE(DATA_SOURCE(TYPE => 'STREAMING'))
);

CREATE PIPE IF NOT EXISTS STORE_INVENTORY_EVENTS_PIPE
AS COPY INTO STORE_INVENTORY_EVENTS
  (EVENT_ID, EVENT_TS, STORE_SK, ITEM_SK, ON_HAND_QTY, ON_ORDER_QTY, IN_TRANSIT_QTY)
FROM (
  SELECT
    $1:event_id::VARCHAR,
    $1:event_ts::TIMESTAMP_NTZ,
    $1:store_sk::NUMBER,
    $1:item_sk::NUMBER,
    $1:on_hand_qty::NUMBER,
    $1:on_order_qty::NUMBER,
    $1:in_transit_qty::NUMBER
  FROM TABLE(DATA_SOURCE(TYPE => 'STREAMING'))
);

GRANT OPERATE, MONITOR ON PIPE STORE_SALES_EVENTS_PIPE TO ROLE RETAIL_DEMO_ENGINEER;
GRANT OPERATE, MONITOR ON PIPE STORE_INVENTORY_EVENTS_PIPE TO ROLE RETAIL_DEMO_ENGINEER;
