-- Optional least-privilege role for a dedicated producer identity.
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS RETAIL_DEMO_STREAMER;
GRANT USAGE ON DATABASE RETAIL_DEMO TO ROLE RETAIL_DEMO_STREAMER;
GRANT USAGE ON SCHEMA RETAIL_DEMO.RAW TO ROLE RETAIL_DEMO_STREAMER;
GRANT INSERT ON TABLE RETAIL_DEMO.RAW.STORE_SALES_EVENTS TO ROLE RETAIL_DEMO_STREAMER;
GRANT INSERT ON TABLE RETAIL_DEMO.RAW.STORE_INVENTORY_EVENTS TO ROLE RETAIL_DEMO_STREAMER;
GRANT OPERATE ON PIPE RETAIL_DEMO.RAW.STORE_SALES_EVENTS_PIPE TO ROLE RETAIL_DEMO_STREAMER;
GRANT OPERATE ON PIPE RETAIL_DEMO.RAW.STORE_INVENTORY_EVENTS_PIPE TO ROLE RETAIL_DEMO_STREAMER;
GRANT ROLE RETAIL_DEMO_STREAMER TO USER <% streaming_user_name %>;
