USE ROLE RETAIL_DEMO_ENGINEER;
USE WAREHOUSE RETAIL_DEMO_WH;
USE DATABASE RETAIL_DEMO;
USE SCHEMA SERVING;

CREATE OR REPLACE SECURE VIEW MERCHANT_SCORECARD AS
SELECT * FROM RETAIL_DEMO.ANALYTICS.MERCHANT_SCORECARD;

CREATE OR REPLACE SECURE VIEW MERCHANT_PROBLEMS AS
SELECT * FROM RETAIL_DEMO.ANALYTICS.MERCHANT_PROBLEMS;

CREATE OR REPLACE SECURE VIEW ROOT_CAUSE_EVIDENCE AS
SELECT * FROM RETAIL_DEMO.ANALYTICS.ROOT_CAUSE_EVIDENCE;

GRANT SELECT ON VIEW MERCHANT_SCORECARD TO ROLE RETAIL_DEMO_METABASE;
GRANT SELECT ON VIEW MERCHANT_PROBLEMS TO ROLE RETAIL_DEMO_METABASE;
GRANT SELECT ON VIEW ROOT_CAUSE_EVIDENCE TO ROLE RETAIL_DEMO_METABASE;
