-- Select a deterministic, dense cohort from TPCDS_SF10TCL. This is the only
-- potentially large scan in the build. Keep the X-Small warehouse suspended
-- until this step and inspect the query profile before scaling up.
USE ROLE RETAIL_DEMO_ENGINEER;
USE WAREHOUSE RETAIL_DEMO_WH;
USE DATABASE RETAIL_DEMO;
USE SCHEMA CONFIG;

CREATE OR REPLACE TEMP TABLE SALES_BOUNDS AS
SELECT
  MAX(d.D_DATE) AS BASELINE_END_DATE,
  DATEADD(DAY, -83, MAX(d.D_DATE)) AS BASELINE_START_DATE
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES ss
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM d
  ON d.D_DATE_SK = ss.SS_SOLD_DATE_SK;

CREATE OR REPLACE TEMP TABLE CATEGORY_CANDIDATE AS
SELECT
  i.I_CATEGORY AS CATEGORY,
  COUNT(DISTINCT ss.SS_ITEM_SK) AS ITEM_COUNT,
  COUNT(DISTINCT ss.SS_STORE_SK) AS STORE_COUNT,
  COUNT(*) AS SALES_ROW_COUNT,
  SUM(ss.SS_QUANTITY) AS UNITS
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES ss
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM d
  ON d.D_DATE_SK = ss.SS_SOLD_DATE_SK
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM i
  ON i.I_ITEM_SK = ss.SS_ITEM_SK
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE st
  ON st.S_STORE_SK = ss.SS_STORE_SK
CROSS JOIN SALES_BOUNDS b
WHERE d.D_DATE BETWEEN b.BASELINE_START_DATE AND b.BASELINE_END_DATE
  AND i.I_CATEGORY IS NOT NULL
GROUP BY i.I_CATEGORY
HAVING COUNT(DISTINCT ss.SS_ITEM_SK) >= 20
   AND COUNT(DISTINCT ss.SS_STORE_SK) >= 25
QUALIFY ROW_NUMBER() OVER (ORDER BY SALES_ROW_COUNT DESC, CATEGORY) = 1;

CREATE OR REPLACE TABLE DEMO_SCENARIO AS
SELECT
  'MDI_DEMO_V1'::VARCHAR AS SCENARIO_ID,
  c.CATEGORY,
  b.BASELINE_START_DATE,
  b.BASELINE_END_DATE,
  DATEADD(DAY, 1, b.BASELINE_END_DATE) AS SIMULATION_DATE,
  84::NUMBER AS BASELINE_DAYS,
  20::NUMBER AS EXPECTED_ITEM_COUNT,
  25::NUMBER AS EXPECTED_STORE_COUNT
FROM CATEGORY_CANDIDATE c
CROSS JOIN SALES_BOUNDS b;

CREATE OR REPLACE TEMP TABLE RANKED_ITEMS AS
SELECT
  ss.SS_ITEM_SK AS ITEM_SK,
  SUM(ss.SS_QUANTITY) AS UNITS,
  COUNT(DISTINCT ss.SS_STORE_SK) AS SELLING_STORES
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES ss
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM d
  ON d.D_DATE_SK = ss.SS_SOLD_DATE_SK
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM i
  ON i.I_ITEM_SK = ss.SS_ITEM_SK
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE st
  ON st.S_STORE_SK = ss.SS_STORE_SK
CROSS JOIN DEMO_SCENARIO s
WHERE d.D_DATE BETWEEN s.BASELINE_START_DATE AND s.BASELINE_END_DATE
  AND i.I_CATEGORY = s.CATEGORY
GROUP BY ss.SS_ITEM_SK
HAVING COUNT(DISTINCT ss.SS_STORE_SK) >= 8
QUALIFY ROW_NUMBER() OVER (ORDER BY UNITS DESC, ITEM_SK) <= 20;

CREATE OR REPLACE TABLE DEMO_SCENARIO_ITEM AS
SELECT
  s.SCENARIO_ID,
  i.I_ITEM_SK AS ITEM_SK,
  i.I_ITEM_ID AS ITEM_ID,
  i.I_ITEM_DESC AS ITEM_DESC,
  i.I_CATEGORY AS CATEGORY,
  i.I_CLASS AS CLASS,
  i.I_BRAND AS BRAND,
  i.I_MANUFACT_ID AS MANUFACTURER_ID,
  i.I_MANUFACT AS MANUFACTURER_NAME,
  i.I_CURRENT_PRICE AS CURRENT_PRICE,
  i.I_WHOLESALE_COST AS WHOLESALE_COST
FROM RANKED_ITEMS r
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM i
  ON i.I_ITEM_SK = r.ITEM_SK
CROSS JOIN DEMO_SCENARIO s;

CREATE OR REPLACE TEMP TABLE RANKED_STORES AS
SELECT
  ss.SS_STORE_SK AS STORE_SK,
  COUNT(DISTINCT ss.SS_ITEM_SK) AS ITEM_COVERAGE,
  SUM(ss.SS_QUANTITY) AS UNITS
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES ss
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM d
  ON d.D_DATE_SK = ss.SS_SOLD_DATE_SK
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE st
  ON st.S_STORE_SK = ss.SS_STORE_SK
JOIN DEMO_SCENARIO_ITEM i
  ON i.ITEM_SK = ss.SS_ITEM_SK
CROSS JOIN DEMO_SCENARIO s
WHERE d.D_DATE BETWEEN s.BASELINE_START_DATE AND s.BASELINE_END_DATE
GROUP BY ss.SS_STORE_SK
HAVING COUNT(DISTINCT ss.SS_ITEM_SK) >= 3
QUALIFY ROW_NUMBER() OVER (ORDER BY ITEM_COVERAGE DESC, UNITS DESC, STORE_SK) <= 25;

CREATE OR REPLACE TABLE DEMO_SCENARIO_STORE AS
SELECT
  s.SCENARIO_ID,
  st.S_STORE_SK AS STORE_SK,
  st.S_STORE_ID AS STORE_ID,
  st.S_STORE_NAME AS STORE_NAME,
  st.S_CITY AS CITY,
  st.S_STATE AS STATE,
  st.S_MARKET_ID AS MARKET_ID,
  st.S_DIVISION_ID AS DIVISION_ID
FROM RANKED_STORES r
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE st
  ON st.S_STORE_SK = r.STORE_SK
CROSS JOIN DEMO_SCENARIO s;

CREATE OR REPLACE TABLE DEMO_SCENARIO_ITEM_STORE AS
WITH DAILY AS (
  SELECT
    ss.SS_STORE_SK AS STORE_SK,
    ss.SS_ITEM_SK AS ITEM_SK,
    d.D_DATE AS SALES_DATE,
    SUM(ss.SS_QUANTITY) AS UNITS,
    SUM(ss.SS_EXT_SALES_PRICE) AS SALES,
    SUM(ss.SS_NET_PROFIT) AS MARGIN
  FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES ss
  JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM d
    ON d.D_DATE_SK = ss.SS_SOLD_DATE_SK
  JOIN DEMO_SCENARIO_ITEM i ON i.ITEM_SK = ss.SS_ITEM_SK
  JOIN DEMO_SCENARIO_STORE st ON st.STORE_SK = ss.SS_STORE_SK
  CROSS JOIN DEMO_SCENARIO s
  WHERE d.D_DATE BETWEEN s.BASELINE_START_DATE AND s.BASELINE_END_DATE
  GROUP BY ss.SS_STORE_SK, ss.SS_ITEM_SK, d.D_DATE
)
SELECT
  s.SCENARIO_ID,
  d.STORE_SK,
  d.ITEM_SK,
  SUM(d.UNITS) / s.BASELINE_DAYS AS AVG_DAILY_UNITS,
  SUM(d.SALES) / s.BASELINE_DAYS AS AVG_DAILY_SALES,
  SUM(d.MARGIN) / s.BASELINE_DAYS AS AVG_DAILY_MARGIN,
  COUNT(*) AS ACTIVE_DAYS
FROM DAILY d
CROSS JOIN DEMO_SCENARIO s
GROUP BY s.SCENARIO_ID, s.BASELINE_DAYS, d.STORE_SK, d.ITEM_SK
HAVING SUM(d.UNITS) > 0;

CREATE OR REPLACE VIEW COHORT_QUALIFICATION AS
SELECT 'category-selected' AS CHECK_NAME,
       IFF((SELECT COUNT(*) FROM DEMO_SCENARIO) = 1, 'PASS', 'FAIL') AS STATUS,
       'exactly one category and scenario' AS DETAIL
UNION ALL
SELECT 'item-count', IFF(COUNT(*) = 20, 'PASS', 'FAIL'), COUNT(*) || ' selected items'
FROM DEMO_SCENARIO_ITEM
UNION ALL
SELECT 'store-count', IFF(COUNT(*) = 25, 'PASS', 'FAIL'), COUNT(*) || ' selected stores'
FROM DEMO_SCENARIO_STORE
UNION ALL
SELECT 'pair-density', IFF(COUNT(*) >= 100, 'PASS', 'FAIL'), COUNT(*) || ' observed item/store pairs'
FROM DEMO_SCENARIO_ITEM_STORE
UNION ALL
SELECT 'items-cover-eight-stores',
       IFF(MIN(STORE_COUNT) >= 8, 'PASS', 'FAIL'),
       MIN(STORE_COUNT) || ' minimum stores per item'
FROM (
  SELECT ITEM_SK, COUNT(DISTINCT STORE_SK) AS STORE_COUNT
  FROM DEMO_SCENARIO_ITEM_STORE GROUP BY ITEM_SK
);

SELECT * FROM COHORT_QUALIFICATION ORDER BY CHECK_NAME;
