-- Unload the small cohort contract to the landing stage. Download these four
-- files to data/cohort/ before running the local generator.
USE ROLE RETAIL_DEMO_ENGINEER;
USE WAREHOUSE RETAIL_DEMO_WH;
USE DATABASE RETAIL_DEMO;

COPY INTO @SEED.S3_LANDING_STAGE/cohort/scenario.parquet
FROM (SELECT * FROM CONFIG.DEMO_SCENARIO)
FILE_FORMAT = (FORMAT_NAME = SEED.PARQUET_FORMAT)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

COPY INTO @SEED.S3_LANDING_STAGE/cohort/items.parquet
FROM (
  SELECT ITEM_SK, ITEM_ID, ITEM_DESC, CATEGORY, CLASS, BRAND,
         MANUFACTURER_ID, MANUFACTURER_NAME, CURRENT_PRICE, WHOLESALE_COST
  FROM CONFIG.DEMO_SCENARIO_ITEM ORDER BY ITEM_SK
)
FILE_FORMAT = (FORMAT_NAME = SEED.PARQUET_FORMAT)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

COPY INTO @SEED.S3_LANDING_STAGE/cohort/stores.parquet
FROM (
  SELECT STORE_SK, STORE_ID, STORE_NAME, CITY, STATE, MARKET_ID, DIVISION_ID
  FROM CONFIG.DEMO_SCENARIO_STORE ORDER BY STORE_SK
)
FILE_FORMAT = (FORMAT_NAME = SEED.PARQUET_FORMAT)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

COPY INTO @SEED.S3_LANDING_STAGE/cohort/item_store_baseline.parquet
FROM (
  SELECT STORE_SK, ITEM_SK, AVG_DAILY_UNITS, AVG_DAILY_SALES,
         AVG_DAILY_MARGIN, ACTIVE_DAYS
  FROM CONFIG.DEMO_SCENARIO_ITEM_STORE ORDER BY STORE_SK, ITEM_SK
)
FILE_FORMAT = (FORMAT_NAME = SEED.PARQUET_FORMAT)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;
