-- Phase 0: bootstrap the Openflow roles and least-privilege grants.
-- Run through an ACCOUNTADMIN connection. This file is idempotent and does
-- not create a deployment, runtime, integration, secret, or database.
--
-- Required Snowflake CLI definition:
--   openflow_user_name: user who will open the runtime canvas. Its default
--     role must not be ACCOUNTADMIN; DEFAULT_SECONDARY_ROLES = ('ALL') is
--     recommended by Snowflake.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS OPENFLOW_ADMIN;
GRANT ROLE OPENFLOW_ADMIN TO ROLE ACCOUNTADMIN;
GRANT ROLE OPENFLOW_ADMIN TO USER <% openflow_user_name %>;
GRANT CREATE OPENFLOW DEPLOYMENT ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE OPENFLOW_ADMIN;

CREATE ROLE IF NOT EXISTS OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL TO ROLE OPENFLOW_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE RETAIL_DEMO_WH
  TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT USAGE ON DATABASE RETAIL_DEMO TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT USAGE ON SCHEMA RETAIL_DEMO.RAW TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT INSERT, SELECT ON TABLE RETAIL_DEMO.RAW.SUPPLIER
  TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT INSERT, SELECT ON TABLE RETAIL_DEMO.RAW.PURCHASE_ORDER
  TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT INSERT, SELECT ON TABLE RETAIL_DEMO.RAW.RECEIPT
  TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT INSERT, SELECT ON TABLE RETAIL_DEMO.RAW.MERCHANT_PLAN
  TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
