-- Gen 2 bootstrap. The S3 external access integration is account- and region-
-- specific; create it by following the official Openflow setup guide and pass
-- its identifier as s3_eai.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS OPENFLOW_ADMIN;
GRANT ROLE OPENFLOW_ADMIN TO USER <% openflow_user_name %>;
GRANT CREATE OPENFLOW DEPLOYMENT ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE OPENFLOW_ADMIN;

CREATE ROLE IF NOT EXISTS OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT USAGE, OPERATE ON WAREHOUSE RETAIL_DEMO_WH
  TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT USAGE ON DATABASE RETAIL_DEMO TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT USAGE ON SCHEMA RETAIL_DEMO.RAW TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT INSERT, SELECT ON TABLE RETAIL_DEMO.RAW.SUPPLIER
  TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT INSERT, SELECT ON TABLE RETAIL_DEMO.RAW.PURCHASE_ORDER
  TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT INSERT, SELECT ON TABLE RETAIL_DEMO.RAW.RECEIPT
  TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT INSERT, SELECT ON TABLE RETAIL_DEMO.RAW.MERCHANT_PLAN
  TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
GRANT USAGE ON INTEGRATION <% s3_eai %> TO ROLE OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;

USE ROLE OPENFLOW_ADMIN;
CREATE DATABASE IF NOT EXISTS RETAIL_DEMO_OPENFLOW_CONTROL;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME;
GRANT CREATE OPENFLOW RUNTIME ON SCHEMA RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME
  TO ROLE OPENFLOW_ADMIN;
GRANT CREATE OPENFLOW CONNECTOR ON SCHEMA RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME
  TO ROLE OPENFLOW_ADMIN;

CREATE OPENFLOW DEPLOYMENT IF NOT EXISTS RETAIL_DEMO_OPENFLOW
  DEPLOYMENT_TYPE = SNOWFLAKE
  DISPLAY_NAME = 'Retail demo gen 2 deployment'
  COMMENT = 'Disposable Openflow deployment for the merchant tutorial';

CREATE OPENFLOW RUNTIME IF NOT EXISTS RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME.RETAIL_DEMO_RUNTIME
  IN DEPLOYMENT RETAIL_DEMO_OPENFLOW
  NODE_TYPE = SMALL
  NODE_TYPE_TIER = 'S1'
  MIN_NODES = 1
  MAX_NODES = 1
  EXECUTE_AS_ROLE = OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL
  EXTERNAL_ACCESS_INTEGRATIONS = (<% s3_eai %>)
  DISPLAY_NAME = 'Retail demo runtime';

SELECT SYSTEM$WAIT_FOR_STABLE_OPENFLOW_DEPLOYMENTS(900, 'RETAIL_DEMO_OPENFLOW');
SELECT SYSTEM$WAIT_FOR_STABLE_OPENFLOW_RUNTIMES(
  600,
  'RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME.RETAIL_DEMO_RUNTIME'
);
