-- Read-only Openflow gate for the locked 20-item x 25-store tutorial cohort.
-- INGESTED_AT is intentionally excluded: it is operational wall-clock metadata.

USE ROLE OPENFLOW_ADMIN;
USE WAREHOUSE RETAIL_DEMO_WH;

WITH actual AS (
  SELECT 'SUPPLIER' AS FEED, COUNT(*) AS ACTUAL_ROWS, 5 AS EXPECTED_ROWS
  FROM RETAIL_DEMO.RAW.SUPPLIER
  UNION ALL
  SELECT 'PURCHASE_ORDER', COUNT(*), 500
  FROM RETAIL_DEMO.RAW.PURCHASE_ORDER
  UNION ALL
  SELECT 'RECEIPT', COUNT(*), 500
  FROM RETAIL_DEMO.RAW.RECEIPT
  UNION ALL
  SELECT 'MERCHANT_PLAN', COUNT(*), 175
  FROM RETAIL_DEMO.RAW.MERCHANT_PLAN
)
SELECT
  'row-count-' || LOWER(FEED) AS CHECK_NAME,
  IFF(ACTUAL_ROWS = EXPECTED_ROWS, 'PASS', 'FAIL') AS STATUS,
  ACTUAL_ROWS || ' of ' || EXPECTED_ROWS || ' rows' AS DETAIL
FROM actual
ORDER BY FEED;

WITH reconciliation AS (
  SELECT
    COUNT(*) AS PO_ROWS,
    COUNT(r.RECEIPT_ID) AS MATCHED_RECEIPTS,
    COUNT_IF(r.RECEIPT_ID IS NULL) AS MISSING_RECEIPTS
  FROM RETAIL_DEMO.RAW.PURCHASE_ORDER p
  LEFT JOIN RETAIL_DEMO.RAW.RECEIPT r ON r.PO_ID = p.PO_ID
)
SELECT
  'po-receipt-reconciliation' AS CHECK_NAME,
  IFF(PO_ROWS = 500 AND MATCHED_RECEIPTS = 500 AND MISSING_RECEIPTS = 0, 'PASS', 'FAIL')
    AS STATUS,
  PO_ROWS || ' POs, ' || MATCHED_RECEIPTS || ' matched receipts, '
    || MISSING_RECEIPTS || ' missing receipts' AS DETAIL
FROM reconciliation;

WITH scenario AS (
  SELECT SIMULATION_DATE
  FROM RETAIL_DEMO.CONFIG.DEMO_SCENARIO
), business_dates AS (
  SELECT 'purchase-order' AS FEED, ORDER_DATE AS BUSINESS_DATE
  FROM RETAIL_DEMO.RAW.PURCHASE_ORDER
  UNION ALL
  SELECT 'purchase-order-expected-receipt', EXPECTED_RECEIPT_DATE
  FROM RETAIL_DEMO.RAW.PURCHASE_ORDER
  UNION ALL
  SELECT 'purchase-order-updated', UPDATED_AT::DATE
  FROM RETAIL_DEMO.RAW.PURCHASE_ORDER
  UNION ALL
  SELECT 'receipt', RECEIPT_DATE
  FROM RETAIL_DEMO.RAW.RECEIPT
  UNION ALL
  SELECT 'receipt-updated', UPDATED_AT::DATE
  FROM RETAIL_DEMO.RAW.RECEIPT
  UNION ALL
  SELECT 'merchant-plan', PLAN_DATE
  FROM RETAIL_DEMO.RAW.MERCHANT_PLAN
  UNION ALL
  SELECT 'merchant-plan-updated', UPDATED_AT::DATE
  FROM RETAIL_DEMO.RAW.MERCHANT_PLAN
)
SELECT
  'scenario-clock-' || FEED AS CHECK_NAME,
  IFF(
    MIN(BUSINESS_DATE) >= DATEADD(DAY, -6, s.SIMULATION_DATE)
      AND MAX(BUSINESS_DATE) <= s.SIMULATION_DATE,
    'PASS',
    'FAIL'
  ) AS STATUS,
  MIN(BUSINESS_DATE) || ' through ' || MAX(BUSINESS_DATE)
    || '; scenario date ' || s.SIMULATION_DATE AS DETAIL
FROM business_dates
CROSS JOIN scenario s
GROUP BY FEED, s.SIMULATION_DATE
ORDER BY FEED;
