-- Destructive and irreversible. Run through the role-restricted
-- OPENFLOW_ADMIN connection only after all custom-flow processors are stopped,
-- queues are empty, required evidence is exported, and SHOW OPENFLOW CONNECTORS
-- confirms that no connector objects depend on this runtime.

ALTER OPENFLOW RUNTIME
  RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME.RETAIL_DEMO_RUNTIME SUSPEND;
SELECT SYSTEM$WAIT_FOR_OPENFLOW_RUNTIME_STATUS(
  600,
  'SUSPENDED',
  'RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME.RETAIL_DEMO_RUNTIME'
);

ALTER OPENFLOW RUNTIME
  RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME.RETAIL_DEMO_RUNTIME TERMINATE;
SELECT SYSTEM$WAIT_FOR_STABLE_OPENFLOW_RUNTIMES(
  600,
  'RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME.RETAIL_DEMO_RUNTIME'
);
DROP OPENFLOW RUNTIME
  RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME.RETAIL_DEMO_RUNTIME;

ALTER OPENFLOW DEPLOYMENT RETAIL_DEMO_OPENFLOW TERMINATE;
SELECT SYSTEM$WAIT_FOR_STABLE_OPENFLOW_DEPLOYMENTS(900, 'RETAIL_DEMO_OPENFLOW');
DROP OPENFLOW DEPLOYMENT RETAIL_DEMO_OPENFLOW;

DROP EXTERNAL ACCESS INTEGRATION IF EXISTS RETAIL_DEMO_OPENFLOW_S3_EAI;
DROP DATABASE IF EXISTS RETAIL_DEMO_OPENFLOW_CONTROL;
