-- Run only after exporting any flow definition you intend to keep.
USE ROLE OPENFLOW_ADMIN;
DROP OPENFLOW RUNTIME IF EXISTS RETAIL_DEMO_OPENFLOW_CONTROL.RUNTIME.RETAIL_DEMO_RUNTIME;
DROP OPENFLOW DEPLOYMENT IF EXISTS RETAIL_DEMO_OPENFLOW;

USE ROLE ACCOUNTADMIN;
DROP DATABASE IF EXISTS RETAIL_DEMO_OPENFLOW_CONTROL;
DROP ROLE IF EXISTS OPENFLOW_RETAIL_DEMO_EXECUTE_AS_RL;
DROP ROLE IF EXISTS OPENFLOW_ADMIN;
