USE ROLE RETAIL_DEMO_ENGINEER;
USE WAREHOUSE RETAIL_DEMO_WH;
USE DATABASE RETAIL_DEMO;
USE SCHEMA VALIDATION;

CREATE OR REPLACE VIEW DEMO_READINESS AS
SELECT
  'cohort-qualified' AS CHECK_NAME,
  IFF(COUNT_IF(STATUS <> 'PASS') = 0, 'PASS', 'FAIL') AS STATUS,
  COUNT_IF(STATUS = 'PASS') || '/' || COUNT(*) || ' cohort checks passed' AS DETAIL
FROM RETAIL_DEMO.CONFIG.COHORT_QUALIFICATION
UNION ALL
SELECT
  'iceberg-inventory-90-days',
  IFF(DATEDIFF(DAY, MIN(SNAPSHOT_DATE), MAX(SNAPSHOT_DATE)) + 1 = 90, 'PASS', 'FAIL'),
  COUNT(*) || ' rows across ' || (DATEDIFF(DAY, MIN(SNAPSHOT_DATE), MAX(SNAPSHOT_DATE)) + 1) || ' days'
FROM RETAIL_DEMO.LAKEHOUSE.INVENTORY_HISTORY
UNION ALL
SELECT
  'iceberg-po-history', IFF(COUNT(*) > 0, 'PASS', 'FAIL'), COUNT(*) || ' historical purchase orders'
FROM RETAIL_DEMO.LAKEHOUSE.PURCHASE_ORDER_HISTORY
UNION ALL
SELECT
  'iceberg-supplier-history-90-days',
  IFF(DATEDIFF(DAY, MIN(PERFORMANCE_DATE), MAX(PERFORMANCE_DATE)) + 1 = 90, 'PASS', 'FAIL'),
  COUNT(*) || ' supplier-day rows'
FROM RETAIL_DEMO.LAKEHOUSE.SUPPLIER_PERFORMANCE_HISTORY
UNION ALL
SELECT
  'openflow-suppliers', IFF(COUNT(*) = 5, 'PASS', 'FAIL'), COUNT(*) || ' current suppliers'
FROM RETAIL_DEMO.RAW.SUPPLIER
UNION ALL
SELECT
  'openflow-po-receipts',
  IFF(COUNT_IF(r.PO_ID IS NULL OR r.RECEIVED_QTY + r.REJECTED_QTY > p.ORDERED_QTY) = 0
      AND COUNT(*) > 0, 'PASS', 'FAIL'),
  COUNT(*) || ' purchase orders reconciled'
FROM RETAIL_DEMO.RAW.PURCHASE_ORDER p
LEFT JOIN RETAIL_DEMO.RAW.RECEIPT r ON r.PO_ID = p.PO_ID
UNION ALL
SELECT
  'streaming-seven-hot-days',
  IFF(COUNT(DISTINCT TO_DATE(EVENT_TS)) = 7, 'PASS', 'FAIL'),
  COUNT(*) || ' sales events across ' || COUNT(DISTINCT TO_DATE(EVENT_TS)) || ' days'
FROM RETAIL_DEMO.RAW.STORE_SALES_EVENTS
UNION ALL
SELECT
  'streaming-no-orphans',
  IFF(COUNT_IF(i.ITEM_SK IS NULL OR st.STORE_SK IS NULL) = 0 AND COUNT(*) > 0, 'PASS', 'FAIL'),
  COUNT(*) || ' inventory events checked'
FROM RETAIL_DEMO.RAW.STORE_INVENTORY_EVENTS e
LEFT JOIN RETAIL_DEMO.CONFIG.DEMO_SCENARIO_ITEM i ON i.ITEM_SK = e.ITEM_SK
LEFT JOIN RETAIL_DEMO.CONFIG.DEMO_SCENARIO_STORE st ON st.STORE_SK = e.STORE_SK
UNION ALL
SELECT
  'healthy-control-exists',
  IFF(COUNT_IF(HEALTH_STATUS = 'HEALTHY') > 0, 'PASS', 'FAIL'),
  COUNT_IF(HEALTH_STATUS = 'HEALTHY') || ' healthy item/store controls'
FROM RETAIL_DEMO.ANALYTICS.ITEM_STORE_HEALTH
UNION ALL
SELECT
  'failure-cohort-exists',
  IFF(COUNT_IF(ROOT_CAUSE = 'SUPPLIER_UNDERFILL') > 0, 'PASS', 'FAIL'),
  COUNT_IF(ROOT_CAUSE = 'SUPPLIER_UNDERFILL') || ' supplier-underfill problems'
FROM RETAIL_DEMO.ANALYTICS.MERCHANT_PROBLEMS
UNION ALL
SELECT
  'supplier-failure-precedes-risk',
  IFF(COUNT_IF(FILL_RATE < 0.60 AND DAYS_OF_SUPPLY <= 2) > 0, 'PASS', 'FAIL'),
  COUNT_IF(FILL_RATE < 0.60 AND DAYS_OF_SUPPLY <= 2) || ' linked failures'
FROM RETAIL_DEMO.ANALYTICS.MERCHANT_PROBLEMS
UNION ALL
SELECT
  'serving-detail-reconciles',
  IFF(ABS(s.SCORECARD_EXPOSURE - d.DETAIL_EXPOSURE) < 0.01, 'PASS', 'FAIL'),
  'scorecard=' || s.SCORECARD_EXPOSURE || ', detail=' || d.DETAIL_EXPOSURE
FROM (
  SELECT COALESCE(SUM(ESTIMATED_LOST_SALES), 0) AS SCORECARD_EXPOSURE
  FROM RETAIL_DEMO.SERVING.MERCHANT_SCORECARD
) s
CROSS JOIN (
  SELECT COALESCE(SUM(ESTIMATED_LOST_SALES), 0) AS DETAIL_EXPOSURE
  FROM RETAIL_DEMO.SERVING.MERCHANT_PROBLEMS
) d;

CREATE OR REPLACE PROCEDURE ASSERT_DEMO_READY()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  NOT_READY EXCEPTION (-20001, 'DEMO_READINESS contains one or more failed checks');
  FAILURE_COUNT INTEGER;
BEGIN
  SELECT COUNT_IF(STATUS <> 'PASS') INTO :FAILURE_COUNT
  FROM RETAIL_DEMO.VALIDATION.DEMO_READINESS;
  IF (FAILURE_COUNT > 0) THEN
    RAISE NOT_READY;
  END IF;
  RETURN 'PASS: all demo readiness checks succeeded';
END;
$$;

SELECT * FROM DEMO_READINESS ORDER BY CHECK_NAME;
