-- Snowflake owns the Iceberg metadata and writes data/metadata beneath each
-- BASE_LOCATION. Do not manually copy files into the iceberg/ prefix.
USE ROLE RETAIL_DEMO_ENGINEER;
USE WAREHOUSE RETAIL_DEMO_WH;
USE DATABASE RETAIL_DEMO;
USE SCHEMA LAKEHOUSE;

CREATE ICEBERG TABLE IF NOT EXISTS INVENTORY_HISTORY (
  SNAPSHOT_DATE DATE,
  STORE_SK NUMBER,
  ITEM_SK NUMBER,
  ON_HAND_QTY NUMBER,
  ON_ORDER_QTY NUMBER,
  IN_TRANSIT_QTY NUMBER,
  DAYS_OF_SUPPLY NUMBER(18,3)
)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '<% external_volume %>'
  BASE_LOCATION = 'inventory_history';

CREATE ICEBERG TABLE IF NOT EXISTS PURCHASE_ORDER_HISTORY (
  PO_ID VARCHAR,
  SUPPLIER_ID VARCHAR,
  STORE_SK NUMBER,
  ITEM_SK NUMBER,
  ORDER_DATE DATE,
  EXPECTED_RECEIPT_DATE DATE,
  ACTUAL_RECEIPT_DATE DATE,
  ORDERED_QTY NUMBER,
  RECEIVED_QTY NUMBER,
  FILL_RATE NUMBER(10,4),
  ON_TIME BOOLEAN
)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '<% external_volume %>'
  BASE_LOCATION = 'purchase_order_history';

CREATE ICEBERG TABLE IF NOT EXISTS SUPPLIER_PERFORMANCE_HISTORY (
  PERFORMANCE_DATE DATE,
  SUPPLIER_ID VARCHAR,
  FILL_RATE NUMBER(10,4),
  ON_TIME_RATE NUMBER(10,4),
  OPEN_PO_COUNT NUMBER,
  AVG_LEAD_TIME_DAYS NUMBER(10,2)
)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '<% external_volume %>'
  BASE_LOCATION = 'supplier_performance_history';

COPY INTO INVENTORY_HISTORY
  (SNAPSHOT_DATE, STORE_SK, ITEM_SK, ON_HAND_QTY, ON_ORDER_QTY, IN_TRANSIT_QTY, DAYS_OF_SUPPLY)
FROM (
  SELECT
    $1:snapshot_date::DATE, $1:store_sk::NUMBER, $1:item_sk::NUMBER,
    $1:on_hand_qty::NUMBER, $1:on_order_qty::NUMBER, $1:in_transit_qty::NUMBER,
    $1:days_of_supply::NUMBER(18,3)
  FROM @RETAIL_DEMO.SEED.S3_LANDING_STAGE/history/inventory_history/
    (FILE_FORMAT => 'RETAIL_DEMO.SEED.PARQUET_FORMAT')
)
FORCE = FALSE;

COPY INTO PURCHASE_ORDER_HISTORY
  (PO_ID, SUPPLIER_ID, STORE_SK, ITEM_SK, ORDER_DATE, EXPECTED_RECEIPT_DATE,
   ACTUAL_RECEIPT_DATE, ORDERED_QTY, RECEIVED_QTY, FILL_RATE, ON_TIME)
FROM (
  SELECT
    $1:po_id::VARCHAR, $1:supplier_id::VARCHAR, $1:store_sk::NUMBER, $1:item_sk::NUMBER,
    $1:order_date::DATE, $1:expected_receipt_date::DATE, $1:actual_receipt_date::DATE,
    $1:ordered_qty::NUMBER, $1:received_qty::NUMBER, $1:fill_rate::NUMBER(10,4),
    $1:on_time::BOOLEAN
  FROM @RETAIL_DEMO.SEED.S3_LANDING_STAGE/history/purchase_order_history/
    (FILE_FORMAT => 'RETAIL_DEMO.SEED.PARQUET_FORMAT')
)
FORCE = FALSE;

COPY INTO SUPPLIER_PERFORMANCE_HISTORY
  (PERFORMANCE_DATE, SUPPLIER_ID, FILL_RATE, ON_TIME_RATE, OPEN_PO_COUNT, AVG_LEAD_TIME_DAYS)
FROM (
  SELECT
    $1:performance_date::DATE, $1:supplier_id::VARCHAR, $1:fill_rate::NUMBER(10,4),
    $1:on_time_rate::NUMBER(10,4), $1:open_po_count::NUMBER,
    $1:avg_lead_time_days::NUMBER(10,2)
  FROM @RETAIL_DEMO.SEED.S3_LANDING_STAGE/history/supplier_performance_history/
    (FILE_FORMAT => 'RETAIL_DEMO.SEED.PARQUET_FORMAT')
)
FORCE = FALSE;
